### ISSUE TITLE
fix the game, why did you make this game broken intentionally ? 

### ISSUE THREAD

**Issue by View-my-Git-Lab-krafi** [JHPDEVS/keypop_Pygame_Rhythm_Game#1]
**on line 13** 
remove thing line nothing called settings and maybe thats why that music wave animation is broken 
`
#from Settings import *`

**on line 20**
```

HEIGHT2 = 640 # height of a bar
WIDTH2 = 445# width of a barFPS = 60
```

**on line 46**
`
w, h = WIDTH2,HEIGHT2`

**on line 54**

```

#onset_frames = librosa.onset.onset_detect(x, sr=sr, wait=1, pre_avg=1, post_avg=1, pre_max=1, post_max=1)
onset_frames = librosa.onset.onset_detect(y=x, sr=sr, wait=1, pre_avg=1, post_avg=1, pre_max=1, post_max=1)
```

**on line 77: provide the font or** 
```

        self.basic_font = pg.font.Font(None, 15)  # 폰트 설정
        self.title_font = pg.font.Font(None, 15)  # 폰트 설정
        self.combo_font = pg.font.Font(None, 30)  # 폰트 설정
```

**on line 106**

```
        TITLE = "keypop_Pygame_Rhythm_Game"
        pg.display.set_caption(TITLE)
```

**"I'm not sure if this code is actually yours, but leaving a project without any license appears unprofessional. Someone could potentially claim it as their own. I suggest you consider using the GNU General Public License version 2 (GPL-2) to protect your code."**

**Comment by View-my-Git-Lab-krafi** [comment]
https://github.com/EndersteveGamer/Friday-night-funkin-with-Pygame/issues/14

https://www.youtube.com/watch?v=cvojJoBlbGk&t=183s&ab_channel=JHP

**Comment by JHPDEVS** [comment]
Committed the missing file and corrected the error, buddy
I made it roughly as a homework, so the quality is low
I wish you best of luck.
